import type { Issue } from './types';

export const issues: Issue[] = [
  {
    id: 'CZ-001',
    category: 'Pothole',
    description: 'Large pothole on the main road causing traffic issues. It has been there for over a week.',
    location: { lat: 28.6139, lng: 77.2090, address: '123 Main St, Connaught Place, New Delhi' },
    imageUrl: 'https://picsum.photos/seed/pothole1/600/400',
    imageHint: 'pothole road',
    reportedAt: '2024-07-15T09:30:00Z',
    status: 'In Progress',
    updates: [
      { status: 'In Progress', date: '2024-07-18T14:00:00Z', description: 'Repair crew assigned. Work scheduled to begin tomorrow morning.' },
      { status: 'In Review', date: '2024-07-16T11:00:00Z', description: 'Issue verified. Assessing severity and required resources.' },
      { status: 'Reported', date: '2024-07-15T09:30:00Z', description: 'Issue reported by a citizen.' },
    ],
    reporter: { name: 'Ravi Kumar', avatarUrl: 'https://picsum.photos/seed/user1/40/40' },
    estimatedCompletion: '2024-07-20',
  },
  {
    id: 'CZ-002',
    category: 'Streetlight',
    description: 'Streetlight is flickering and often goes out completely at night. It is a safety concern for the residents.',
    location: { lat: 19.0760, lng: 72.8777, address: '456 Park Avenue, Bandra, Mumbai' },
    imageUrl: 'https://picsum.photos/seed/light2/600/400',
    imageHint: 'broken streetlight',
    reportedAt: '2024-07-14T21:00:00Z',
    status: 'Resolved',
    updates: [
        { status: 'Resolved', date: '2024-07-17T16:20:00Z', description: 'The streetlight bulb and wiring have been replaced and tested.' },
        { status: 'In Progress', date: '2024-07-16T10:00:00Z', description: 'Technician dispatched to the location.' },
        { status: 'In Review', date: '2024-07-15T09:00:00Z', description: 'Report acknowledged. Awaiting technician availability.' },
        { status: 'Reported', date: '2024-07-14T21:00:00Z', description: 'Issue reported by a citizen.' },
    ],
    reporter: { name: 'Priya Sharma', avatarUrl: 'https://picsum.photos/seed/user2/40/40' },
  },
  {
    id: 'CZ-003',
    category: 'Waste Management',
    description: 'Garbage bin is overflowing and waste is scattered on the street. Needs immediate collection.',
    location: { lat: 12.9716, lng: 77.5946, address: '789 Garden Road, Koramangala, Bengaluru' },
    imageUrl: 'https://picsum.photos/seed/waste3/600/400',
    imageHint: 'overflowing trash',
    reportedAt: '2024-07-18T08:00:00Z',
    status: 'In Review',
    updates: [
        { status: 'In Review', date: '2024-07-18T10:00:00Z', description: 'Report has been forwarded to the sanitation department.' },
        { status: 'Reported', date: '2024-07-18T08:00:00Z', description: 'Issue reported by a citizen.' },
    ],
    reporter: { name: 'Ankit Jain', avatarUrl: 'https://picsum.photos/seed/user3/40/40' },
    estimatedCompletion: '2024-07-19',
  },
  {
    id: 'CZ-004',
    category: 'Other',
    description: 'Broken public bench at the park. It has sharp edges and is a hazard.',
    location: { lat: 22.5726, lng: 88.3639, address: '101 Lake View, Salt Lake, Kolkata' },
    imageUrl: 'https://picsum.photos/seed/bench4/600/400',
    imageHint: 'broken bench',
    reportedAt: '2024-07-17T15:45:00Z',
    status: 'Reported',
    updates: [
        { status: 'Reported', date: '2024-07-17T15:45:00Z', description: 'Issue reported by a citizen.' },
    ],
    reporter: { name: 'Sunita Roy', avatarUrl: 'https://picsum.photos/seed/user4/40/40' },
  },
  {
    id: 'CZ-005',
    category: 'Pothole',
    description: 'Multiple small potholes forming a cluster near the school.',
    location: { lat: 13.0827, lng: 80.2707, address: '21 School Lane, Anna Nagar, Chennai' },
    imageUrl: 'https://picsum.photos/seed/pothole5/600/400',
    imageHint: 'road damage',
    reportedAt: '2024-07-19T11:00:00Z',
    status: 'Reported',
    updates: [
        { status: 'Reported', date: '2024-07-19T11:00:00Z', description: 'Issue reported. Awaiting review.' },
    ],
    reporter: { name: 'Murali Krishna', avatarUrl: 'https://picsum.photos/seed/user5/40/40' },
  },
];
